import type { CountrySource } from '../src/data/countrySchema'

const accessedAt = '2026-08-12'
const referenceLicense = 'Copyrighted reference material; linked, not copied'

export const countrySources: CountrySource[] = [
  {
    id: 'world-cities',
    name: 'SimpleMaps World Cities Database',
    publisher: 'SimpleMaps / world-cities-json contributors',
    version: 'world-cities-json 1.0.1',
    url: 'https://simplemaps.com/data/world-cities',
    license: 'Creative Commons Attribution 4.0 International (CC BY 4.0)',
  },
  {
    id: 'scio-geo-city-review',
    name: 'Scio Geo reviewed city selection',
    publisher: 'Scio Geo project',
    version: '2026-08-13',
    url: 'https://github.com/1COOS/scio-geo/blob/main/scripts/city-content.ts',
    license: 'Repository-owned reviewed educational metadata',
  },
  {
    id: 'noaa-ocean',
    name: 'Ocean and seafloor education references',
    publisher: 'NOAA Ocean Service',
    accessedAt: '2026-08-13',
    url: 'https://oceanservice.noaa.gov/education/',
    license: 'U.S. federal government reference material; linked, not copied',
  },
  {
    id: 'gebco-gazetteer',
    name: 'GEBCO Gazetteer of Undersea Feature Names',
    publisher: 'GEBCO Sub-Committee on Undersea Feature Names',
    accessedAt: '2026-08-13',
    url: 'https://www.gebco.net/data_and_products/undersea_feature_names/',
    license: 'Referenced for undersea feature names and locations',
  },
  {
    id: 'iho-oceans-seas',
    name: 'Limits of Oceans and Seas reference',
    publisher: 'International Hydrographic Organization',
    accessedAt: '2026-08-13',
    url: 'https://iho.int/en/standards-and-specifications',
    license: 'Copyrighted reference material; linked, not copied',
  },
  {
    id: 'marine-regions',
    name: 'Marine Regions geographic names reference',
    publisher: 'Flanders Marine Institute',
    accessedAt: '2026-08-13',
    url: 'https://www.marineregions.org/',
    license: 'Copyrighted reference database; linked, not copied',
  },
  {
    id: 'natural-earth-marine',
    name: 'Natural Earth geography marine polygons',
    publisher: 'Natural Earth contributors',
    version:
      'Natural Earth 5.1.0 1:10m; SHA-256 a2d3395904c41e718e02c3ec5bc988712164c524c236fad32d95d282ca303b2a',
    accessedAt: '2026-08-14',
    url: 'https://www.naturalearthdata.com/downloads/10m-physical-vectors/10m-physical-labels/',
    license:
      'Public domain marine polygons; selected and simplified by Scio Geo',
  },
  {
    id: 'britannica-ocean',
    name: 'Ocean overview',
    publisher: 'Encyclopaedia Britannica',
    accessedAt: '2026-08-13',
    url: 'https://www.britannica.com/science/ocean',
    license: referenceLicense,
  },
  {
    id: 'natural-earth-lakes',
    name: 'Natural Earth lake polygons',
    publisher: 'Natural Earth contributors',
    version:
      'Natural Earth 5.0.0 1:10m; SHA-256 0803a06f9c3cb4671d89b68c48b142aad9366ba40f665245e12a913fbc61722a',
    accessedAt: '2026-08-17',
    url: 'https://www.naturalearthdata.com/downloads/10m-physical-vectors/10m-lakes/',
    license: 'Public domain lake polygons; selected and simplified by Scio Geo',
  },
  {
    id: 'britannica-lake',
    name: 'Lake overview',
    publisher: 'Encyclopaedia Britannica',
    accessedAt: '2026-08-17',
    url: 'https://www.britannica.com/science/lake',
    license: referenceLicense,
  },
  {
    id: 'natural-earth-rivers',
    name: 'Natural Earth rivers and lake centerlines',
    publisher: 'Natural Earth contributors',
    version:
      'Natural Earth 5.0.0 1:10m; SHA-256 ded71b01870855ccfe19b51f2ec14c9bb48fae23c0e9f3c11974d426433b5c38',
    accessedAt: '2026-08-13',
    url: 'https://naturalearthdata.com/downloads/10m-physical-vectors/10m-rivers-lake-centerlines/',
    license:
      'Public domain vector data; main stems selected and simplified by Scio Geo',
  },
  {
    id: 'natural-earth-mountains',
    name: 'Natural Earth geography region polygons',
    publisher: 'Natural Earth contributors',
    version:
      'Natural Earth 5.0.0 1:10m; SHA-256 cb7b9db200284ed1551f20eacc7f3333e9b5f311c19f7cb2670694529f688682',
    accessedAt: '2026-08-14',
    url: 'https://www.naturalearthdata.com/downloads/10m-physical-vectors/10m-physical-labels/',
    license:
      'Public domain range envelopes; Scio Geo derives reviewed educational ridge lines',
  },
  {
    id: 'natural-earth-deserts',
    name: 'Natural Earth geography region polygons',
    publisher: 'Natural Earth contributors',
    version:
      'Natural Earth 5.0.0 1:10m; SHA-256 cb7b9db200284ed1551f20eacc7f3333e9b5f311c19f7cb2670694529f688682',
    accessedAt: '2026-08-16',
    url: 'https://www.naturalearthdata.com/downloads/10m-physical-vectors/10m-physical-labels/',
    license:
      'Public domain desert-region polygons; selected and simplified by Scio Geo',
  },
  {
    id: 'britannica-deserts',
    name: 'Desert landform reference collection',
    publisher: 'Encyclopaedia Britannica',
    accessedAt: '2026-08-16',
    url: 'https://www.britannica.com/science/desert',
    license: referenceLicense,
  },
  {
    id: 'unesco-world-heritage',
    name: 'World Heritage List',
    publisher: 'UNESCO World Heritage Centre',
    accessedAt: '2026-08-17',
    url: 'https://whc.unesco.org/en/list/',
    license: 'Official reference material; linked, not copied',
  },
  {
    id: 'bavaria-neuschwanstein',
    name: 'Neuschwanstein Castle',
    publisher: 'Bavarian Palace Department',
    accessedAt: '2026-08-17',
    url: 'https://www.neuschwanstein.de/englisch/tourist/',
    license: 'Official reference material; linked, not copied',
  },
  {
    id: 'scio-geo-landmark-review',
    name: 'Scio Geo reviewed world landmark catalogue',
    publisher: 'Scio Geo project',
    version: '2026-08-17',
    url: 'https://github.com/1COOS/scio-geo/blob/main/src/data/landmarks.ts',
    license: 'Repository-owned reviewed educational metadata',
  },
  {
    id: 'britannica-mountains',
    name: 'Mountain and mountain-range reference collection',
    publisher: 'Encyclopaedia Britannica',
    accessedAt: '2026-08-14',
    url: 'https://www.britannica.com/science/mountain-landform',
    license: referenceLicense,
  },
  {
    id: 'mountain-peak-review',
    name: 'Scio Geo reviewed mountain and highest-peak catalogue',
    publisher: 'Scio Geo project',
    version: '2026-08-14',
    url: 'https://github.com/1COOS/scio-geo/blob/main/src/data/mountainRanges.ts',
    license:
      'Repository-owned educational summaries reviewed against linked geographic references',
  },
  {
    id: 'china-mountain-review',
    name: 'China mountain and peak reference review',
    publisher: 'Scio Geo review of public Chinese geographic references',
    accessedAt: '2026-08-14',
    url: 'https://www.mnr.gov.cn/english/',
    license: 'Official reference material; linked, not copied',
  },
  {
    id: 'usgs-mountain-peaks',
    name: 'United States mountain elevations and locations',
    publisher: 'U.S. Geological Survey',
    accessedAt: '2026-08-14',
    url: 'https://www.usgs.gov/programs/national-geospatial-program',
    license: 'U.S. federal government reference material; linked, not copied',
  },
  {
    id: 'geoscience-australia-mountains',
    name: 'Australian mountain and elevation references',
    publisher: 'Geoscience Australia',
    accessedAt: '2026-08-14',
    url: 'https://www.ga.gov.au/scientific-topics/national-location-information',
    license: 'Australian government reference material; linked, not copied',
  },
  {
    id: 'linz-mountain-peaks',
    name: 'New Zealand geographic names and elevation references',
    publisher: 'Land Information New Zealand',
    accessedAt: '2026-08-14',
    url: 'https://www.linz.govt.nz/products-services/place-names',
    license: 'New Zealand government reference material; linked, not copied',
  },
  {
    id: 'china-river-source-review',
    name: 'China major-river source reach review',
    publisher: 'Scio Geo review of public Ministry of Water Resources material',
    accessedAt: '2026-08-13',
    url: 'http://www.mwr.gov.cn/english/',
    license:
      'Official reference material; short repository-reviewed educational supplement',
  },
  {
    id: 'mekong-source-review',
    name: 'Mekong and Lancang source reach review',
    publisher: 'Mekong River Commission and Scio Geo review',
    accessedAt: '2026-08-13',
    url: 'https://www.mrcmekong.org/',
    license:
      'Official reference material; short repository-reviewed educational supplement',
  },
  {
    id: 'canadian-hydrographic-network',
    name: 'Canadian Hydrographic Network reference',
    publisher: 'Natural Resources Canada',
    accessedAt: '2026-08-13',
    url: 'https://open.canada.ca/data/en/dataset/a4b190fe-e090-4e6d-881e-b87956c07977',
    license:
      'Open Government Licence - Canada; referenced for review, not copied directly into shipped geometry',
  },
  {
    id: 'peru-ana-rivers',
    name: 'Peru national hydrographic reference',
    publisher: 'Autoridad Nacional del Agua del Peru',
    accessedAt: '2026-08-13',
    url: 'https://www.ana.gob.pe/',
    license:
      'Official reference used to review a short repository-authored educational supplement',
  },
  {
    id: 'brazil-ana-rivers',
    name: 'Brazil national hydrographic reference',
    publisher: 'Agencia Nacional de Aguas e Saneamento Basico',
    accessedAt: '2026-08-13',
    url: 'https://metadados.snirh.gov.br/',
    license:
      'Official reference used to review a short repository-authored Paraguay main-stem supplement',
  },
  {
    id: 'britannica-rivers',
    name: 'Major rivers reference collection',
    publisher: 'Encyclopaedia Britannica',
    accessedAt: '2026-08-13',
    url: 'https://www.britannica.com/science/river',
    license: referenceLicense,
  },
  {
    id: 'britannica-canals',
    name: 'Canal engineering and history references',
    publisher: 'Encyclopaedia Britannica',
    accessedAt: '2026-08-13',
    url: 'https://www.britannica.com/technology/canal-waterway',
    license: referenceLicense,
  },
  {
    id: 'unesco-grand-canal',
    name: 'The Grand Canal',
    publisher: 'UNESCO World Heritage Centre',
    accessedAt: '2026-08-13',
    url: 'https://whc.unesco.org/en/list/1443/',
    license: referenceLicense,
  },
  {
    id: 'suez-canal-authority',
    name: 'Suez Canal overview',
    publisher: 'Suez Canal Authority',
    accessedAt: '2026-08-13',
    url: 'https://www.suezcanal.gov.eg/English/About/SuezCanal/Pages/CanalCharacteristics.aspx',
    license: 'Official reference material; linked, not copied',
  },
  {
    id: 'panama-canal-authority',
    name: 'Panama Canal overview',
    publisher: 'Panama Canal Authority',
    accessedAt: '2026-08-13',
    url: 'https://pancanal.com/en/history-of-the-panama-canal/',
    license: 'Official reference material; linked, not copied',
  },
  {
    id: 'world-countries',
    name: 'World Countries dataset',
    publisher: 'mledoze/countries contributors',
    version: '5.1.0',
    url: 'https://github.com/mledoze/countries',
    license: 'Open Database License (ODbL) 1.0',
  },
  {
    id: 'world-bank-population',
    name: 'Population, total (SP.POP.TOTL)',
    publisher: 'World Bank',
    version: '2025 latest available values',
    accessedAt: '2026-08-17',
    url: 'https://data.worldbank.org/indicator/SP.POP.TOTL',
    license: 'Creative Commons Attribution 4.0 International (CC BY 4.0)',
  },
  {
    id: 'cia-world-factbook',
    name: 'The World Factbook country profiles',
    publisher: 'U.S. Central Intelligence Agency / factbook.json mirror',
    version: 'factbook.json c8cfe21cd019d7748a6b0d57a75d6a77f5ec6ac6',
    accessedAt: '2026-08-31',
    url: 'https://github.com/factbook/factbook.json/tree/c8cfe21cd019d7748a6b0d57a75d6a77f5ec6ac6',
    license:
      'U.S. Government public-domain source data; repository-authored complete Chinese translations',
  },
  {
    id: 'vatican-population',
    name: 'Vatican City population statistics',
    publisher: 'Governorate of Vatican City State',
    version: 'Updated 31 December 2024',
    accessedAt: '2026-08-17',
    url: 'https://www.vaticanstate.va/en/state-and-government/general-informations/population.html',
    license: 'Official reference material; population total transcribed',
  },
  ...[
    [
      'un-security-council-members',
      'Current Members of the United Nations Security Council',
      'United Nations Security Council',
      'https://main.un.org/securitycouncil/en/content/current-members',
    ],
    [
      'g7-members',
      'The G7 and its members',
      'Council of the European Union',
      'https://www.consilium.europa.eu/en/policies/g7-summit/',
    ],
    [
      'g20-members',
      'About the G20',
      'Group of Twenty',
      'https://g20.org/about-g20/',
    ],
    [
      'brics-members',
      'About the BRICS',
      'BRICS Brazil 2025 Presidency',
      'https://brics.br/en/about-the-brics',
    ],
    [
      'saudi-brics-status',
      'Saudi Arabia participates in the BRICS summit as an invited country',
      'Saudi Press Agency',
      'https://www.spa.gov.sa/en/N2586193',
    ],
    [
      'commonwealth-member-countries',
      'Commonwealth member countries',
      'The Commonwealth',
      'https://thecommonwealth.org/our-member-countries',
    ],
    [
      'eu-country-profiles',
      'EU country profiles',
      'European Union',
      'https://european-union.europa.eu/principles-countries-history/country-profiles_en',
    ],
    [
      'asean-member-states',
      'ASEAN Member States',
      'Association of Southeast Asian Nations',
      'https://asean.org/member-states/',
    ],
    [
      'african-union-member-states',
      'African Union Member States',
      'African Union',
      'https://au.int/en/member_states/countryprofiles2',
    ],
    [
      'arab-league-member-states',
      'League of Arab States member countries',
      'League of Arab States',
      'https://www.lasportal.org/en/aboutlas/Pages/CountryData.aspx',
    ],
    [
      'gcc-member-states',
      'GCC Member States',
      'Gulf Cooperation Council',
      'https://www.gcc-sg.org/en/AboutUs/MemberStates/Pages/default.aspx',
    ],
    [
      'mercosur-member-states',
      'MERCOSUR countries',
      'Southern Common Market',
      'https://www.mercosur.int/en/about-mercosur/mercosur-countries/',
    ],
    [
      'caricom-member-states',
      'CARICOM Member States and Associate Members',
      'Caribbean Community',
      'https://caricom.org/member-states-and-associate-members/',
    ],
    [
      'opec-member-countries',
      'OPEC Member Countries',
      'Organization of the Petroleum Exporting Countries',
      'https://www.opec.org/opec-web/en/about-us/25.html',
    ],
    [
      'nato-member-countries',
      'NATO member countries',
      'North Atlantic Treaty Organization',
      'https://www.nato.int/en/about-us/organization/nato-member-countries',
    ],
    [
      'sco-member-states',
      'Shanghai Cooperation Organisation member states',
      'Shanghai Cooperation Organisation',
      'https://eng.sectsco.org/',
    ],
    [
      'quad-partners',
      'The Quad',
      'Australian Department of Foreign Affairs and Trade',
      'https://www.dfat.gov.au/international-relations/regional-architecture/quad',
    ],
    [
      'aukus-partners',
      'AUKUS',
      'Government of the United Kingdom',
      'https://www.gov.uk/government/collections/aukus',
    ],
    [
      'oecd-member-countries',
      'OECD members and partners',
      'Organisation for Economic Co-operation and Development',
      'https://www.oecd.org/en/about/members-partners.html',
    ],
  ].map(([id, name, publisher, url]) => ({
    id,
    name,
    publisher,
    accessedAt: '2026-09-05',
    url,
    license:
      'Official reference material; membership and short repository-authored summaries transcribed',
  })),
  ...[
    [
      'britannica-australia',
      'Australia',
      'https://www.britannica.com/place/Australia',
    ],
    ['britannica-brazil', 'Brazil', 'https://www.britannica.com/place/Brazil'],
    ['britannica-china', 'China', 'https://www.britannica.com/place/China'],
    ['britannica-egypt', 'Egypt', 'https://www.britannica.com/place/Egypt'],
    ['britannica-france', 'France', 'https://www.britannica.com/place/France'],
    ['britannica-india', 'India', 'https://www.britannica.com/place/India'],
    [
      'britannica-indonesia',
      'Indonesia',
      'https://www.britannica.com/place/Indonesia',
    ],
    ['britannica-japan', 'Japan', 'https://www.britannica.com/place/Japan'],
    ['britannica-mexico', 'Mexico', 'https://www.britannica.com/place/Mexico'],
    ['britannica-russia', 'Russia', 'https://www.britannica.com/place/Russia'],
    [
      'britannica-south-africa',
      'South Africa',
      'https://www.britannica.com/place/South-Africa',
    ],
    [
      'britannica-united-states',
      'United States',
      'https://www.britannica.com/place/United-States',
    ],
  ].map(([id, countryName, url]) => ({
    id,
    name: `${countryName} overview`,
    publisher: 'Encyclopaedia Britannica',
    accessedAt,
    url,
    license: referenceLicense,
  })),
  {
    id: 'wwf-giant-panda',
    name: 'Giant Panda',
    publisher: 'World Wildlife Fund',
    accessedAt,
    url: 'https://www.worldwildlife.org/species/giant-panda',
    license: referenceLicense,
  },
  {
    id: 'nps-yellowstone',
    name: 'History of Yellowstone National Park',
    publisher: 'U.S. National Park Service',
    accessedAt,
    url: 'https://www.nps.gov/yell/learn/historyculture/index.htm',
    license: 'U.S. federal government reference material; linked, not copied',
  },
  {
    id: 'unesco-giza',
    name: 'Memphis and its Necropolis – the Pyramid Fields from Giza to Dahshur',
    publisher: 'UNESCO World Heritage Centre',
    accessedAt,
    url: 'https://whc.unesco.org/en/list/86/',
    license: referenceLicense,
  },
  {
    id: 'unesco-great-barrier-reef',
    name: 'Great Barrier Reef',
    publisher: 'UNESCO World Heritage Centre',
    accessedAt,
    url: 'https://whc.unesco.org/en/list/154/',
    license: referenceLicense,
  },
]
